[versions]
arrow = "2.2.1.1"
jackson = "2.20.1"
kotlin = "2.3.10"
ktlint = "14.0.1"
mavenPublish = "0.35.0"
spring = "6.2.14"
mockk = "1.14.7"
wiremock = "3.13.2"
junit = "6.0.2"
asm = "9.9.1"
dokka = "2.1.0"

[libraries]
arrowCore = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
jacksonKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
springWeb = { module = "org.springframework:spring-web", version.ref = "spring" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlinCompilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinTestJunit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asmTree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }

[bundles]
testCommon = ["junitJupiter", "junitParams", "kotlinTest", "kotlinTestJunit5"]

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
